#############################################################################
# Makefile for building: Stegosaurus
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Jan 21 16:28:36 2012
# Project:  Stegosaurus.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Stegosaurus.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
NVCC          = nvcc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
NVCCFLAGS     = -m64 -arch=sm_20
INCPATH       = -I/usr/lib64/qt/mkspecs/linux-g++-64 -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include/QtGui -I/usr/lib64/qt/include -I/opt/cuda/include -Icore -Igui -I.
#LINK         = g++
LINK          = nvcc
#LFLAGS       = -m64 -Wl,-O1 -Wl,-rpath,/opt/qt-4.7.4/lib
LFLAGS        = -m64 -arch=sm_20
#LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/lib64/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt/lib -lQtGui -L/usr/lib64/qt/lib -L/usr/X11R6/lib64 -lQtCore -lpthread -lcublas
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = core/Stegosaurus.cpp \
		core/Stegosaurus.cu \
		core/Stegosaurus_IO.cpp \
		core/Stegosaurus_Estimate.cu \
		core/Stegosaurus_KL.cu \
		gui/ConfigDock.cpp \
		gui/FeatureDock.cpp \
		gui/GraphDock.cpp \
		gui/StegoFrame.cpp \
		gui/StegoWidgets.cpp \
		gui/TableDock.cpp moc_ConfigDock.cpp \
		moc_FeatureDock.cpp \
		moc_GraphDock.cpp \
		moc_StegoFrame.cpp \
		moc_StegoWidgets.cpp \
		moc_TableDock.cpp
OBJECTS       = Stegosaurus.o \
		Stegosaurus.cu.o \
		Stegosaurus_Estimate.cu.o \
		Stegosaurus_KL.cu.o \
		Stegosaurus_IO.o \
		ConfigDock.o \
		FeatureDock.o \
		GraphDock.o \
		StegoFrame.o \
		StegoWidgets.o \
		TableDock.o \
		moc_ConfigDock.o \
		moc_FeatureDock.o \
		moc_GraphDock.o \
		moc_StegoFrame.o \
		moc_StegoWidgets.o \
		moc_TableDock.o
DIST          = /usr/lib64/qt/mkspecs/common/g++.conf \
		/usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		Stegosaurus.pro
QMAKE_TARGET  = Stegosaurus
DESTDIR       = 
TARGET        = Stegosaurus

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

.cu.o:
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Stegosaurus.pro  /usr/lib64/qt/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt/mkspecs/common/g++.conf \
		/usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt/lib/libQtGui.prl \
		/usr/lib64/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile Stegosaurus.pro
/usr/lib64/qt/mkspecs/common/g++.conf:
/usr/lib64/qt/mkspecs/common/unix.conf:
/usr/lib64/qt/mkspecs/common/linux.conf:
/usr/lib64/qt/mkspecs/qconfig.pri:
/usr/lib64/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib64/qt/mkspecs/features/qt_functions.prf:
/usr/lib64/qt/mkspecs/features/qt_config.prf:
/usr/lib64/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt/mkspecs/features/default_pre.prf:
/usr/lib64/qt/mkspecs/features/release.prf:
/usr/lib64/qt/mkspecs/features/default_post.prf:
/usr/lib64/qt/mkspecs/features/warn_on.prf:
/usr/lib64/qt/mkspecs/features/qt.prf:
/usr/lib64/qt/mkspecs/features/unix/thread.prf:
/usr/lib64/qt/mkspecs/features/moc.prf:
/usr/lib64/qt/mkspecs/features/resources.prf:
/usr/lib64/qt/mkspecs/features/uic.prf:
/usr/lib64/qt/mkspecs/features/yacc.prf:
/usr/lib64/qt/mkspecs/features/lex.prf:
/usr/lib64/qt/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt/lib/libQtGui.prl:
/usr/lib64/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Stegosaurus.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Stegosaurus1.0.0 || $(MKDIR) .tmp/Stegosaurus1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Stegosaurus1.0.0/ && $(COPY_FILE) --parents core/Stegosaurus.h gui/ConfigDock.h gui/FeatureDock.h gui/GraphDock.h gui/StegoFrame.h gui/StegoWidgets.h gui/TableDock.h .tmp/Stegosaurus1.0.0/ && $(COPY_FILE) --parents core/Stegosaurus.cpp core/Stegosaurus_IO.cpp gui/ConfigDock.cpp gui/FeatureDock.cpp gui/GraphDock.cpp gui/StegoFrame.cpp gui/StegoWidgets.cpp gui/TableDock.cpp .tmp/Stegosaurus1.0.0/ && (cd `dirname .tmp/Stegosaurus1.0.0` && $(TAR) Stegosaurus1.0.0.tar Stegosaurus1.0.0 && $(COMPRESS) Stegosaurus1.0.0.tar) && $(MOVE) `dirname .tmp/Stegosaurus1.0.0`/Stegosaurus1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Stegosaurus1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ConfigDock.cpp moc_FeatureDock.cpp moc_GraphDock.cpp moc_StegoFrame.cpp moc_StegoWidgets.cpp moc_TableDock.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ConfigDock.cpp moc_FeatureDock.cpp moc_GraphDock.cpp moc_StegoFrame.cpp moc_StegoWidgets.cpp moc_TableDock.cpp
moc_ConfigDock.cpp: core/Stegosaurus.h \
		gui/ConfigDock.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/ConfigDock.h -o moc_ConfigDock.cpp

moc_FeatureDock.cpp: core/Stegosaurus.h \
		gui/FeatureDock.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/FeatureDock.h -o moc_FeatureDock.cpp

moc_GraphDock.cpp: core/Stegosaurus.h \
		gui/GraphDock.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/GraphDock.h -o moc_GraphDock.cpp

moc_StegoFrame.cpp: core/Stegosaurus.h \
		gui/FeatureDock.h \
		gui/ConfigDock.h \
		gui/GraphDock.h \
		gui/StegoWidgets.h \
		gui/StegoFrame.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/StegoFrame.h -o moc_StegoFrame.cpp

moc_StegoWidgets.cpp: core/Stegosaurus.h \
		gui/StegoWidgets.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/StegoWidgets.h -o moc_StegoWidgets.cpp

moc_TableDock.cpp: core/Stegosaurus.h \
		gui/TableDock.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) gui/TableDock.h -o moc_TableDock.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Stegosaurus.o: core/Stegosaurus.cpp core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stegosaurus.o core/Stegosaurus.cpp

Stegosaurus.cu.o: core/Stegosaurus.cu
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o Stegosaurus.cu.o core/Stegosaurus.cu

Stegosaurus_IO.o: core/Stegosaurus_IO.cpp core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stegosaurus_IO.o core/Stegosaurus_IO.cpp

Stegosaurus_Estimate.cu.o: core/Stegosaurus_Estimate.cu
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o Stegosaurus_Estimate.cu.o core/Stegosaurus_Estimate.cu

Stegosaurus_KL.cu.o: core/Stegosaurus_KL.cu core/Stegosaurus.h
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o Stegosaurus_KL.cu.o core/Stegosaurus_KL.cu

ConfigDock.o: gui/ConfigDock.cpp gui/ConfigDock.h \
		core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigDock.o gui/ConfigDock.cpp

FeatureDock.o: gui/FeatureDock.cpp gui/FeatureDock.h \
		core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FeatureDock.o gui/FeatureDock.cpp

GraphDock.o: gui/GraphDock.cpp gui/GraphDock.h \
		core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphDock.o gui/GraphDock.cpp

StegoFrame.o: gui/StegoFrame.cpp gui/StegoFrame.h \
		core/Stegosaurus.h \
		gui/FeatureDock.h \
		gui/ConfigDock.h \
		gui/GraphDock.h \
		gui/StegoWidgets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StegoFrame.o gui/StegoFrame.cpp

StegoWidgets.o: gui/StegoWidgets.cpp gui/StegoWidgets.h \
		core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StegoWidgets.o gui/StegoWidgets.cpp

TableDock.o: gui/TableDock.cpp gui/TableDock.h \
		core/Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TableDock.o gui/TableDock.cpp

moc_ConfigDock.o: moc_ConfigDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigDock.o moc_ConfigDock.cpp

moc_FeatureDock.o: moc_FeatureDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FeatureDock.o moc_FeatureDock.cpp

moc_GraphDock.o: moc_GraphDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GraphDock.o moc_GraphDock.cpp

moc_StegoFrame.o: moc_StegoFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StegoFrame.o moc_StegoFrame.cpp

moc_StegoWidgets.o: moc_StegoWidgets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StegoWidgets.o moc_StegoWidgets.cpp

moc_TableDock.o: moc_TableDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TableDock.o moc_TableDock.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

