#############################################################################
# Makefile for building: Stegosaurus
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Nov 23 09:45:21 2011
# Project:  Stegosaurus.pro
# Template: app
# Command: /opt/qt-4.7.4/bin/qmake -o Makefile Stegosaurus.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
NVCC          = nvcc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
NVCCFLAGS     = -m64 -arch=sm_20
INCPATH       = -I/opt/qt-4.7.4/mkspecs/linux-g++-64 -I. -I/opt/qt-4.7.4/include/QtCore -I/opt/qt-4.7.4/include/QtGui -I/opt/qt-4.7.4/include -I/opt/cuda/include -I.
# LINK          = g++
LINK          = nvcc
# LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/opt/qt-4.7.4/lib
LFLAGS        = -m64 -arch=sm_20
LIBS          = $(SUBLIBS)  -L/opt/qt-4.7.4/lib -lQtGui -L/opt/qt-4.7.4/lib -L/usr/X11R6/lib64 -lQtCore -lpthread -lcublas
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qt-4.7.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = StegoFrame.cpp \
		Stegosaurus_Estimate.cpp \
		Stegosaurus_Estimate.cu \
		Stegosaurus_IO.cpp \
		Stegosaurus_KL.cpp \
		Stegosaurus_KL.cu
OBJECTS       = StegoFrame.o \
		Stegosaurus_Estimate.o \
		Stegosaurus_Estimate.cu.o \
		Stegosaurus_IO.o \
		Stegosaurus_KL.o \
		Stegosaurus_KL.cu.o
DIST          = /opt/qt-4.7.4/mkspecs/common/g++.conf \
		/opt/qt-4.7.4/mkspecs/common/unix.conf \
		/opt/qt-4.7.4/mkspecs/common/linux.conf \
		/opt/qt-4.7.4/mkspecs/qconfig.pri \
		/opt/qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-4.7.4/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.4/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.4/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.4/mkspecs/features/release.prf \
		/opt/qt-4.7.4/mkspecs/features/default_post.prf \
		/opt/qt-4.7.4/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.4/mkspecs/features/qt.prf \
		/opt/qt-4.7.4/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.4/mkspecs/features/moc.prf \
		/opt/qt-4.7.4/mkspecs/features/resources.prf \
		/opt/qt-4.7.4/mkspecs/features/uic.prf \
		/opt/qt-4.7.4/mkspecs/features/yacc.prf \
		/opt/qt-4.7.4/mkspecs/features/lex.prf \
		/opt/qt-4.7.4/mkspecs/features/include_source_dir.prf \
		Stegosaurus.pro
QMAKE_TARGET  = Stegosaurus
DESTDIR       = 
TARGET        = Stegosaurus

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

.cu.o:
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Stegosaurus.pro  /opt/qt-4.7.4/mkspecs/linux-g++-64/qmake.conf /opt/qt-4.7.4/mkspecs/common/g++.conf \
		/opt/qt-4.7.4/mkspecs/common/unix.conf \
		/opt/qt-4.7.4/mkspecs/common/linux.conf \
		/opt/qt-4.7.4/mkspecs/qconfig.pri \
		/opt/qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-4.7.4/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.4/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.4/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.4/mkspecs/features/release.prf \
		/opt/qt-4.7.4/mkspecs/features/default_post.prf \
		/opt/qt-4.7.4/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.4/mkspecs/features/qt.prf \
		/opt/qt-4.7.4/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.4/mkspecs/features/moc.prf \
		/opt/qt-4.7.4/mkspecs/features/resources.prf \
		/opt/qt-4.7.4/mkspecs/features/uic.prf \
		/opt/qt-4.7.4/mkspecs/features/yacc.prf \
		/opt/qt-4.7.4/mkspecs/features/lex.prf \
		/opt/qt-4.7.4/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.7.4/lib/libQtGui.prl \
		/opt/qt-4.7.4/lib/libQtCore.prl
	$(QMAKE) -o Makefile Stegosaurus.pro
/opt/qt-4.7.4/mkspecs/common/g++.conf:
/opt/qt-4.7.4/mkspecs/common/unix.conf:
/opt/qt-4.7.4/mkspecs/common/linux.conf:
/opt/qt-4.7.4/mkspecs/qconfig.pri:
/opt/qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/opt/qt-4.7.4/mkspecs/features/qt_functions.prf:
/opt/qt-4.7.4/mkspecs/features/qt_config.prf:
/opt/qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.7.4/mkspecs/features/default_pre.prf:
/opt/qt-4.7.4/mkspecs/features/release.prf:
/opt/qt-4.7.4/mkspecs/features/default_post.prf:
/opt/qt-4.7.4/mkspecs/features/warn_on.prf:
/opt/qt-4.7.4/mkspecs/features/qt.prf:
/opt/qt-4.7.4/mkspecs/features/unix/thread.prf:
/opt/qt-4.7.4/mkspecs/features/moc.prf:
/opt/qt-4.7.4/mkspecs/features/resources.prf:
/opt/qt-4.7.4/mkspecs/features/uic.prf:
/opt/qt-4.7.4/mkspecs/features/yacc.prf:
/opt/qt-4.7.4/mkspecs/features/lex.prf:
/opt/qt-4.7.4/mkspecs/features/include_source_dir.prf:
/opt/qt-4.7.4/lib/libQtGui.prl:
/opt/qt-4.7.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Stegosaurus.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Stegosaurus1.0.0 || $(MKDIR) .tmp/Stegosaurus1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Stegosaurus1.0.0/ && $(COPY_FILE) --parents Stegosaurus.h Stegosaurus_Estimate.h Stegosaurus_IO.h Stegosaurus_KL.h .tmp/Stegosaurus1.0.0/ && $(COPY_FILE) --parents StegoFrame.cpp Stegosaurus_Estimate.cpp Stegosaurus_IO.cpp Stegosaurus_KL.cpp .tmp/Stegosaurus1.0.0/ && (cd `dirname .tmp/Stegosaurus1.0.0` && $(TAR) Stegosaurus1.0.0.tar Stegosaurus1.0.0 && $(COMPRESS) Stegosaurus1.0.0.tar) && $(MOVE) `dirname .tmp/Stegosaurus1.0.0`/Stegosaurus1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Stegosaurus1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

StegoFrame.o: StegoFrame.cpp Stegosaurus_Estimate.h \
		Stegosaurus_IO.h \
		Stegosaurus.h \
		Stegosaurus_KL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StegoFrame.o StegoFrame.cpp

Stegosaurus_Estimate.o: Stegosaurus_Estimate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stegosaurus_Estimate.o Stegosaurus_Estimate.cpp

Stegosaurus_Estimate.cu.o: Stegosaurus_Estimate.cu Stegosaurus_Estimate.h
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o Stegosaurus_Estimate.cu.o Stegosaurus_Estimate.cu

Stegosaurus_IO.o: Stegosaurus_IO.cpp Stegosaurus_IO.h \
		Stegosaurus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stegosaurus_IO.o Stegosaurus_IO.cpp

Stegosaurus_KL.o: Stegosaurus_KL.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stegosaurus_KL.o Stegosaurus_KL.cpp

Stegosaurus_KL.cu.o: Stegosaurus_KL.cu Stegosaurus_KL.h
	$(NVCC) -c $(NVCCFLAGS) $(INCPATH) -o Stegosaurus_KL.cu.o Stegosaurus_KL.cu

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

